### ISSUE TITLE
Nome incorreto da PJ

### ISSUE THREAD

**Issue by marcelodive** [marcelodive/consultorias_fejemg#10]
Olá Marcelo!

Primeiro parabéns pela plataforma, está muito boa.
Sobre bugs e comentários, o nome da PJ está "Produção Jr". Não utilizamos mais este nome, e sim "PJ UFMG".

Abraços. pedro.minchilo@fejemg.org.br

**Comment by mmiguelcj** [comment]
Nome alterado para PJ UFMG. -Done
