### ISSUE TITLE
Nome incorreto da UCJ

### ISSUE THREAD

**Issue by marcelodive** [marcelodive/consultorias_fejemg#7]
Boa tarde, Marcelo!

Tudo bem?

Primeiramente, gostaria de parabenizar a equipe de TI pelo trabalho, ficou bem bacana! Reparei em apenas um pequeno detalhe, a UCJ aparece nas pesquisas com o nome de "UCJ - Consultoria Jr.", quando acredito que o correto deveria ser "UCJ - UFMG Consultoria Júnior".

Abraços, Marcelo Canabrava. marcelo.canabrava@fejemg.org.br

**Comment by mmiguelcj** [comment]
Done.
